#pragma once

typedef enum nodeType {
	NT_COMPILE_UNIT,

	NT_STATEMENT,
	NT_STATEMENTS,
	NT_COMPOUND_STATEMENT,

	T_NUMBER_INTEGER,
	T_IDENTIFIER_INTEGER,

	NT_ASSIGNMENT_EXPRESSION,
	NT_EXPRESSION_ADDITION,
	NT_EXPRESSION_SUBTRACTION,
	NT_EXPRESSION_MULTIPLICATION,
	NT_EXPRESSION_DIVISION,
	NT_EXPRESSION_SQUARE_ROOT,
	NT_EXPRESSION_POWER,

	NT_LESS_EXPRESSION,
	NT_GREATER_EXPRESSION,
	NT_LESS_EQUAL_EXPRESSION,
	NT_GREATER_EQUAL_EXPRESSION,
	NT_EQUAL_EXPRESSION,
	NT_NOT_EQUAL_EXPRESSION,
	NT_AND_EXPRESSION,
	NT_OR_EXPRESSION,
	NT_NOT_EXPRESSION,

	NT_FUNCTION_DEFINITION,
	NT_FUNCTION_CALL_EXPRESSION,
	NT_FORMAL_ARGUMENTS,
	NT_ACTUAL_ARGUMENTS,
	NT_RETURN_STATEMENT,

	NT_IF_STATEMENT,
	NT_WHILE_STATEMENT,
	NT_BREAK_STATEMENT,
	NT_CONTINUE_STATEMENT
} NodeType;

extern const char* g_nodeNames[];
